# config.yaml

# Directory paths
base_dir: "/workspaces/PP5-Cherry-Leaves"
outputs_dir: "outputs"
processed_images_path: "/workspaces/PP5-Cherry-Leaves/inputs/leaves_dataset/cherry-leaves/processed_images"
dataset_name: "cherry-leaves"
dataset_zip_name: "cherry-leaves.zip"
dataset_extract_name: "cherry-leaves"
input_folder: "inputs/leaves_dataset"

kaggle_json_path: "kaggle.json"
kaggle_username: "codeinstitute"

# Other settings
image_size: [100, 100]
target_map:
  healthy: 0
  powdery_mildew: 1
